### ISSUE TITLE
Difference with @rollup/plugin-eslint ?

### ISSUE THREAD

**Issue by jcayzac** [ehutch79/vite-eslint#1]
[The docs list `@rollup/plugin-eslint` as compatible with vite](https://vite-rollup-plugins.patak.dev/#app:~:text=eslint,-Verify), and this works fine:

```ts
import eslint from '@rollup/plugin-eslint'
import { UserConfig } from 'vite'

const config: UserConfig = {
  plugins: [
    {...eslint({include: 'src/**/*.+(js|jsx|ts|tsx)'}), enforce: 'pre'},
  ],
  ...
}

export default config
```

I'm confused about what this plugin does that `@rollup/plugin-eslint` doesn't. Is this mentioned somewhere? Thanks.

**Comment by binaryben** [comment]
Just a quick test, I can see that the overlay works with this plugin but isn't enabled in the official rollup plugin. Is there a way to enable it using the official plugin? If so, I am also curious on the answer.

**Comment by jcayzac** [comment]
@BinaryBen thanks, that's something I hadn't considered since I have the terminal on my screen when I develop so it doesn't affect me. I guess it's important to a large number of people, tho.

**Comment by ehutch79** [comment]
You are correct. This isn't really needed. At the time I had no clue about the 'enforce': 'pre' bit.

There is SOME advantage here, as it's using the newer eslint api, and accesses on a per file basis, instead of part of the stream. It could be useful

Either way I'm archiving the project though.
